In [1]:
import ase
import ase.io
from ase.io import xsf
import pandas as pd
import json
import seaborn as sns
import matplotlib.pyplot as plt
import os
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_pickle("features_MultipleFeaturizer.pkl")
df.head()

,0,1,2,3,4,5,6,7,8,9,...,264,265,266,267,268,269,270,271,272,label
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.777778,64.0,0.130435,0.217391,0.652174,0.000000,1.0,0.209607,0.046579,EE
1,6.000000,10.432235,4.432235,8.954823,1.969882,0.101871,1.076403,0.847193,1.119514e-11,0.171207,...,73.333333,64.0,0.272727,0.454545,0.272727,0.000000,1.0,0.357395,0.079421,EE
2,9.052693,11.479272,2.426579,9.749345,0.864963,0.020033,1.032994,0.959935,2.631480e-02,0.125121,...,15.750000,152.0,0.129032,0.193548,0.483871,0.193548,0.0,0.168813,0.031652,EE
3,10.187778,12.638871,2.451093,11.821840,1.089375,0.050764,1.038073,0.923854,4.593043e-02,0.102799,...,28.000000,229.0,0.200000,0.000000,0.333333,0.466667,0.0,0.265103,0.058912,PE
4,9.198422,14.426225,5.227803,11.335849,2.060251,0.087363,1.131045,0.914155,9.864448e-02,0.120736,...,65.555556,64.0,0.250000,0.250000,0.500000,0.000000,1.0,0.543070,0.104828,EE

In [3]:
df_binary = df.dropna()

In [4]:
df_binary.replace(to_replace='PE', value='EE', inplace=True)
df_binary.replace(to_replace='EE', value=1, inplace=True)
df_binary.replace(to_replace='HBE', value=0, inplace=True)
df_binary.head()

/Users/mohammad/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:5244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,0,1,2,3,4,5,6,7,8,9,...,264,265,266,267,268,269,270,271,272,label
1,6.000000,10.432235,4.432235,8.954823,1.969882,0.101871,1.076403,0.847193,1.119514e-11,0.171207,...,73.333333,64.0,0.272727,0.454545,0.272727,0.000000,1.0,0.357395,0.079421,1
2,9.052693,11.479272,2.426579,9.749345,0.864963,0.020033,1.032994,0.959935,2.631480e-02,0.125121,...,15.750000,152.0,0.129032,0.193548,0.483871,0.193548,0.0,0.168813,0.031652,1
3,10.187778,12.638871,2.451093,11.821840,1.089375,0.050764,1.038073,0.923854,4.593043e-02,0.102799,...,28.000000,229.0,0.200000,0.000000,0.333333,0.466667,0.0,0.265103,0.058912,1
4,9.198422,14.426225,5.227803,11.335849,2.060251,0.087363,1.131045,0.914155,9.864448e-02,0.120736,...,65.555556,64.0,0.250000,0.250000,0.500000,0.000000,1.0,0.543070,0.104828,1
5,4.297802,10.295063,5.997261,8.638179,1.860161,0.115771,1.081628,0.729867,6.790509e-02,0.240869,...,71.724490,12.0,0.181818,0.311688,0.324675,0.181818,1.0,0.400240,0.091499,1

In [5]:
X = df_binary.drop('label', axis = 1).values
y = df_binary['label'].values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
X_train.shape

(1549, 273)

In [10]:
RF = RandomForestClassifier(n_estimators=800)

In [11]:
RF.fit(X_train,y_train)

RandomForestClassifier(n_estimators=800)

In [12]:
pred_RF = RF.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

In [14]:
print(classification_report(y_test, pred_RF))
print("\n")
print(confusion_matrix(y_test, pred_RF))

              precision    recall  f1-score   support

           0       0.81      0.53      0.64       139
           1       0.89      0.97      0.93       525

    accuracy                           0.88       664
   macro avg       0.85      0.75      0.78       664
weighted avg       0.87      0.88      0.87       664



[[ 74  65]
 [ 17 508]]

In [15]:
df_features = pd.read_pickle('features_MultipleFeaturizer_NewBE-AfterRelax.pkl')

In [16]:
df_features

,index,structure,label,binding_energy,0,1,2,3,4,5,...,263,264,265,266,267,268,269,270,271,272
0,0,[[-1.30628722e-16 9.42477908e-18 3.15191547e...,EE,8.383023,NaN,NaN,NaN,NaN,NaN,NaN,...,96.500000,48.750000,64.0,0.131148,0.245902,0.508197,0.114754,True,0.539020,0.101066
1,1,"[[0. 0. 0.] Zn, [1.88856784 1.88856784 2.59480...",PE,65.110991,5.986080,9.860516,3.874436,8.944054,0.845135,0.048350,...,91.714286,87.673469,15.0,0.280000,0.520000,0.200000,0.000000,False,0.742626,0.108618
2,2,"[[ 2.83254907 2.69948155 -0.28118957] Cu, [-2...",EE,10.568737,NaN,NaN,NaN,NaN,NaN,NaN,...,91.000000,94.800000,12.0,0.272727,0.424242,0.303030,0.000000,True,0.447278,0.079241
3,3,"[[1.65250046 1.65250046 0. ] C, [0. 0. ...",EE,22.127216,4.746512,7.092767,2.346255,6.310682,1.042780,0.121800,...,194.000000,0.000000,194.0,0.428571,0.571429,0.000000,0.000000,False,0.058259,0.012946
4,4,"[[1.22839651 2.04898226 3.1660159 ] H, [2.1638...",EE,16.581488,NaN,NaN,NaN,NaN,NaN,NaN,...,122.000000,92.666667,12.0,0.127907,0.197674,0.348837,0.325581,True,0.319141,0.058182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1534,1534,"[[4.30209923 2.74836117 2.65638179] Pb, [1.188...",PE,32.024358,8.248544,13.315222,5.066679,9.743075,1.428859,0.085586,...,107.600000,93.920000,12.0,0.133333,0.226667,0.266667,0.373333,False,0.265103,0.056626
1535,1535,[[3.50603948e-17 1.14850843e+01 3.74878872e+00...,PE,34.086274,NaN,NaN,NaN,NaN,NaN,NaN,...,205.000000,14.666667,194.0,0.875000,0.125000,0.000000,0.000000,True,0.331838,0.049164
1536,1536,"[[4.94447262 5.57299849 1.38528688] Tl, [-0.48...",EE,23.522635,NaN,NaN,NaN,NaN,NaN,NaN,...,113.111111,89.876543,12.0,0.200000,0.266667,0.222222,0.311111,False,0.563121,0.096635
1537,1537,[[-4.34596912e-17 5.06163305e+00 1.34587459e...,PE,70.151743,NaN,NaN,NaN,NaN,NaN,NaN,...,85.909091,91.338843,15.0,0.263158,0.473684,0.078947,0.184211,True,0.917619,0.163036
1538,1538,"[[4.12250308 2.38012826 1.94106298] Cs, [-1.43...",PE,120.368831,6.088889,13.753452,7.664563,8.205041,1.267693,0.083495,...,145.800000,39.264000,152.0,0.138728,0.196532,0.664740,0.000000,False,0.348856,0.026228

In [17]:
df_features = df_features.dropna()
df_features

,index,structure,label,binding_energy,0,1,2,3,4,5,...,263,264,265,266,267,268,269,270,271,272
1,1,"[[0. 0. 0.] Zn, [1.88856784 1.88856784 2.59480...",PE,65.110991,5.986080,9.860516,3.874436,8.944054,0.845135,0.048350,...,91.714286,87.673469,15.0,0.280000,0.520000,0.200000,0.000000,False,0.742626,0.108618
3,3,"[[1.65250046 1.65250046 0. ] C, [0. 0. ...",EE,22.127216,4.746512,7.092767,2.346255,6.310682,1.042780,0.121800,...,194.000000,0.000000,194.0,0.428571,0.571429,0.000000,0.000000,False,0.058259,0.012946
7,7,"[[0. 0. 0.] Zn, [2.41375103e-16 2.36447299e+00...",PE,84.441639,6.000021,7.770575,1.770555,7.180390,0.786913,0.050204,...,166.000000,18.666667,152.0,0.136364,0.181818,0.681818,0.000000,False,0.049365,0.010970
8,8,"[[3.86406762 5.00102798 2.32518033] Sn, [ 0.46...",EE,7.662181,4.549573,9.643946,5.094373,7.659019,1.636851,0.102518,...,59.166667,62.888889,12.0,0.226415,0.396226,0.377358,0.000000,False,0.421664,0.083585
10,10,"[[3.51734466 5.30555643 4.18446412] Fe, [3.517...",EE,21.790253,7.422050,10.817472,3.395422,8.877196,1.226884,0.098833,...,128.666667,107.022222,229.0,0.170455,0.159091,0.670455,0.000000,False,0.121553,0.030253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1528,1528,"[[0. 0. 0.] Eu, [3.24868299 3.2496876 9.28176...",EE,8.554867,5.517106,9.948293,4.431188,6.158639,0.933139,0.141656,...,217.545455,18.743802,229.0,0.213592,0.058252,0.660194,0.067961,False,0.213451,0.013762
1531,1531,"[[0. 0. 0.] Mg, [-1.93145456e-17 6.83650570e-...",EE,12.148489,7.064255,10.425978,3.361723,9.267604,1.468900,0.061282,...,107.333333,57.777778,64.0,0.166667,0.277778,0.555556,0.000000,True,0.493700,0.109711
1533,1533,"[[1.89973269 0. 1.14037415] Ho, [0. ...",EE,15.490123,8.514810,14.651616,6.136806,10.896884,2.503155,0.137145,...,90.000000,69.333333,12.0,0.166667,0.250000,0.277778,0.305556,True,0.705072,0.143093
1534,1534,"[[4.30209923 2.74836117 2.65638179] Pb, [1.188...",PE,32.024358,8.248544,13.315222,5.066679,9.743075,1.428859,0.085586,...,107.600000,93.920000,12.0,0.133333,0.226667,0.266667,0.373333,False,0.265103,0.056626
1538,1538,"[[4.12250308 2.38012826 1.94106298] Cs, [-1.43...",PE,120.368831,6.088889,13.753452,7.664563,8.205041,1.267693,0.083495,...,145.800000,39.264000,152.0,0.138728,0.196532,0.664740,0.000000,False,0.348856,0.026228

In [18]:
df_features.replace(to_replace='PE', value='EE', inplace=True)
df_features.replace(to_replace='EE', value=1, inplace=True)
df_features.replace(to_replace='HBE', value=0, inplace=True)
df_features.head()

/Users/mohammad/anaconda3/lib/python3.7/site-packages/pandas/core/missing.py:94: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= arr == x
/Users/mohammad/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:5244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,index,structure,label,binding_energy,0,1,2,3,4,5,...,263,264,265,266,267,268,269,270,271,272
1,1,"[[0. 0. 0.] Zn, [1.88856784 1.88856784 2.59480...",PE,65.110991,5.986080,9.860516,3.874436,8.944054,0.845135,0.048350,...,91.714286,87.673469,15.0,0.280000,0.520000,0.200000,0.0,False,0.742626,0.108618
3,3,"[[1.65250046 1.65250046 0. ] C, [0. 0. ...",EE,22.127216,4.746512,7.092767,2.346255,6.310682,1.042780,0.121800,...,194.000000,0.000000,194.0,0.428571,0.571429,0.000000,0.0,False,0.058259,0.012946
7,7,"[[0. 0. 0.] Zn, [2.41375103e-16 2.36447299e+00...",PE,84.441639,6.000021,7.770575,1.770555,7.180390,0.786913,0.050204,...,166.000000,18.666667,152.0,0.136364,0.181818,0.681818,0.0,False,0.049365,0.010970
8,8,"[[3.86406762 5.00102798 2.32518033] Sn, [ 0.46...",EE,7.662181,4.549573,9.643946,5.094373,7.659019,1.636851,0.102518,...,59.166667,62.888889,12.0,0.226415,0.396226,0.377358,0.0,False,0.421664,0.083585
10,10,"[[3.51734466 5.30555643 4.18446412] Fe, [3.517...",EE,21.790253,7.422050,10.817472,3.395422,8.877196,1.226884,0.098833,...,128.666667,107.022222,229.0,0.170455,0.159091,0.670455,0.0,False,0.121553,0.030253

In [19]:
X_NewBE = df_features.drop(['label','index', 'structure', 'binding_energy'], axis = 1).values

In [20]:
predictions = RF.predict(X_NewBE)

In [21]:
j = 0
for i in predictions:
        j += i
print('number of 1:', j)
print('number of predictions:', len(predictions))

number of 1: 541
number of predictions: 558

In [22]:
list(predictions).index(0)

21

In [23]:
df_features.iloc[0]

index                                                             1
structure         [[0. 0. 0.] Zn, [1.88856784 1.88856784 2.59480...
label                                                            PE
binding_energy                                            65.110991
0                                                           5.98608
                                        ...
268                                                             0.2
269                                                             0.0
270                                                           False
271                                                        0.742626
272                                                        0.108618
Name: 1, Length: 277, dtype: object